/* Do not edit this file.
 * It exists only to be overwritten by the makefile
 * during build.
 * This is where the global variables XV64_VERSION and
 * XV64_BUILDTIME are initialized
 */

char XV64_VERSION[] = "0.25";
char XV64_BUILDTIME[] = "";
