struct stat;

// system calls
int fork(void);
int procexit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(char*, int);
int mknod(char*, short, short);
int unlink(char*);
int fstat(int fd, struct stat*);
int link(char*, char*);
int mkdir(char*);
int chdir(char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int amblessed(void);
void reboot(void);
int seek(int, int);
unsigned int getppid(void);
int bless(int);
int damn(int);
int isblessed(int);
int bfork(void);
int mkvdev(char*);
int pstate(int);
int pname(int, char*, int);
int ticks(void);
void halt(void);
