#!/usr/bin/env python3

import sys
import re
from pathlib import Path

stack = sys.stdin.read()


def find_best_func(addr, symfilename):
    prefix = "bin/"
    best_func = None
    best_func_addr = None
    offset = 0

    symfile = open(symfilename, "r")
    for line in symfile:
        parts = line.split()
        func_addr_s = parts[0]
        func_name = parts[1]
        func_addr = int(func_addr_s, 16)

        if func_addr < addr:
            if best_func_addr is None or func_addr > best_func_addr:
                best_func = func_name
                best_func_addr = func_addr
                offset = addr - func_addr

    return (best_func, best_func_addr, offset, )


# Example stack trace:
#
# STACK:
#  [0] ffffffff80101aa1
#  [1] ffffffff8010799b
#  [2] ffffffff80109791
#  [3] ffffffff80109516
#  [4] ffffffff8010934a
# HLT
pattern = re.compile(r"\[([0-9]+)\] ([0-9a-f]+)")

for match in pattern.finditer(stack):
    line_num = match.group(1).strip()
    addr_s = match.group(2).strip()
    addr = int(addr_s, 16)

    result = find_best_func(addr, "bin/kernel.sym")
    best_func = result[0]
    best_func_addr = result[1]
    offset = result[2]

    if best_func_addr:
        print("[{}]\t{}\t@ +{} bytes in {}".format(line_num, addr_s, offset, best_func))
    else:
        print("[{}]\t{}\t?".format(line_num, addr_s))
