#!/usr/bin/env python

import sys
import re

def hello(variable):
    print variable

stack = sys.stdin.read()
symfile = open("bin/kernel.sym", "r")

# STACK:
#  [0] ffffffff80101aa1
#  [1] ffffffff8010799b
#  [2] ffffffff80109791
#  [3] ffffffff80109516
#  [4] ffffffff8010934a
# HLT

pattern = re.compile(r"\[([0-9]+)\] ([0-9a-f]+)")
#for match in re.findall(r"\[([0-9]+)\] ([0-9a-f]+)", stack):
for match in pattern.finditer(stack):
    line = match.group(1).strip()
    addr_s = match.group(2).strip()
    addr = int(addr_s, 16)

    best_func = "?"
    best_func_addr = None

    for line in symfile:
        parts = line.split()
        func_addr_s = parts[0]
        func_name = parts[1]
        func_addr = int(func_addr_s, 16)

        if func_addr < addr:
            if best_func_addr is None or func_addr > best_func_addr:
                best_func = func_name
                best_func_addr = func_addr
    print("[{}] {} - {}".format(line, addr_s, best_func))
    print("---")
